services:
  - type: web
    name: isl-connect-backend
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python sign_text12.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
